# Generated by Django 4.1.2 on 2022-11-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='imj',
            new_name='img',
        ),
    ]
