# Generated by Django 4.1.2 on 2022-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_imj_place_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=250)),
                ('teamimg', models.ImageField(upload_to='pics')),
                ('teamdesc', models.TextField()),
            ],
        ),
    ]
